- platform: template
  sensors:
    #----- Count Automations
    count_automations:
      value_template: "{{ states.automation | count }}"

    #----- Count Scripts
    count_scripts:
      value_template: "{{ states.script| count }}"

    #----- Count Device Trackers
    count_device_trackers:
      value_template: "{{ states.device_tracker | count }}"

    #----- Count Binary Sensors
    count_binary_sensors:
      value_template: "{{ states.binary_sensor| count }}"

    #----- Count Sensors
    count_sensors:
      value_template: "{{ states.sensor | count }}"

    #----- Count Switches
    count_switches:
      value_template: "{{ states.switch | count }}"

    #----- Count Zones
    count_zones:
      value_template: "{{ states.zone | count }}"

    #----- Input Booleans
    count_input_booleans:
      value_template: "{{ states.input_boolean | count }}"

    #----- Input Numbers
    count_input_numbers:
      value_template: "{{ states.input_number | count }}"

    #----- Input Texts
    count_input_texts:
      value_template: "{{ states.input_text | count }}"

    #----- Input Selects
    count_input_selects:
      value_template: "{{ states.input_select | count }}"

    #----- Input Date Times
    count_input_datetimes:
      value_template: "{{ states.input_datetime | count }}"
